spring:
  application:
    name: LogsBackend

  kafka:
    bootstrap-servers: kafka:9092

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logs}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    websocket:
      path: /graphql
      connection-init-timeout: 60s
    graphiql:
      enabled: true
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET,POST,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  mvc:
    async:
      request-timeout: -1

server:
  tomcat:
    connection-timeout: -1

logging:
  level:
    root: INFO
    com.example.logsbackend: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.web.socket: DEBUG